### ISSUE TITLE
Could not find env variable ZIMBRA_HOME

### ISSUE THREAD

**Issue by VeelaIT** [sandromello/zbackup#3]
Hello,

I installed Zbackup according to the instructions, but when i want to try to the zbackup -f all command, i will get a "Could not find env variable ZIMBRA_HOME" message.

My server is running Centos 7 with the latest version of Zimbra Opensource.

With kind regards,
Erik

**Comment by sandromello** [comment]
Hello,

As the zimbra user you could execute the following command before running the script:

```
export ZIMBRA_HOME=$(zmlocalconfig -m nokey zimbra_home)
zbackup (...)
```

The `ZIMBRA_HOME` is the root path of your Zimbra installation.
I've updated the docs including this command

**Comment by VeelaIT** [comment]
Thank you very much!
I will continue testing :)

**Comment by sandromello** [comment]
I'll close for now

**Comment by VeelaIT** [comment]
Dear Sandro,

When running the backup command, i'll get:
Backup path does not exists: zimbra_home = /opt/zimbra/backup

The folder exists and i gave it 777 permissions. Still the error exist.
See the following debug command:

```
zbackup -f all --sync --debug
Error running backup: Backup path does not exists: zimbra_home = /opt/zimbra/backup
Traceback (most recent call last):
  File "/opt/zimbra/bin/zbackup", line 89, in <module>
    zcr.run_backup(args.status, fromtime=fromtime, sync=args.sync)
  File "/opt/zimbra/zbackup/common.py", line 155, in run_backup
    raise ZBackupError('Backup path does not exists: %s' % self.bkp_location)
ZBackupError: Backup path does not exists: zimbra_home = /opt/zimbra/backup
```

What am i doing wrong?
Thank you again for you help.

**Comment by sandromello** [comment]
I'm sorry, I gave you a wrong command, the right one is:

```
export ZIMBRA_HOME=$(zmlocalconfig -m nokey zimbra_home)
```
